[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/image",
    "crates/text",
    "crates/path",
    "crates/runtime",
	"crates/winit",
    "examples/basic",
    "examples/egui",
    "examples/web/src-tauri"
]
