[workspace]
resolver = "2"
members = [
    "apps/egui",
    "crates/core",
    "crates/image",
    "crates/text",
    "crates/path",
    "crates/runtime",
	"crates/winit",
    "crates/wasm",
    "apps/web/src-tauri"
]
